Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -3,7 +3,7 @@ name: Deploy Ruby Sinatra App
 on:
   push:
     branches:
-      - main  # Trigger deployment on commits to the 'main' branch
+      - main
 
 jobs:
   deploy:
@@ -28,12 +28,15 @@ jobs:
         SERVER_IP: ${{ secrets.SERVER_IP }}
         SERVER_USER: ${{ secrets.SERVER_USER }}
       run: |
-        ssh -i ~/.ssh/id_ed25519 $SERVER_USER@$SERVER_IP << 'EOF'
+        ssh -i ~/.ssh/id_ed25519 $SERVER_USER@$SERVER_IP <<EOF
+          set -e  # Exit immediately if a command fails
           cd /home/ubuntu/project/geo_tracker
-          git pull origin main  # Pull the latest code from the main branch
-          pkill -f 'ruby.*app.rb' || true  # Stop any running Ruby process for app.rb
-          ruby app.rb -o 0.0.0.0 -p 4567 & # Start the Sinatra application
-          # Wait for the Sinatra app to be ready, by checking the public IP
-          curl --retry 5 --retry-delay 3 --max-time 30 http://54.160.215.88:4567
-         EOF
+          git pull origin main
+          pkill -f 'ruby.*app.rb' || true
+          ruby app.rb -o 0.0.0.0 -p 4567 &
+          sleep 5  # Allow the server some time to start
+        EOF
 
+    - name: Verify App Deployment
+      run: |
+        curl --retry 5 --retry-delay 5 --max-time 10 http://${{ secrets.SERVER_IP }}:4567/user_location
